Models/Payment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saloon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Employee { get; set; }
        public System.DateTime PayDate { get; set; }
        public int Customers { get; set; }
        public int Rate { get; set; }
        public int Amount { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}

Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Saloon.Models;
using Saloon.Helpers;
using System.Data.SqlClient;

namespace Saloon.Controllers
{
     [AuthFilter]
    public class PaymentsController : Controller
    {
        private Connection db = new Connection();

        // GET: Payments
        public ActionResult Index()
        {
            var payments = db.Payments.Include(p => p.User).OrderByDescending(u=>u.PayDate);
            return View(payments.ToList());
        } 
          
        public ActionResult Create()
        { 
            String date = DateTime.Now.ToString("dd/M/yyyy");
            date = date.Replace("-", "/");

            db.PaySalaries(date, SecurityHelper.GetLoginId().ToString());
            return RedirectToAction("Index");
        } 
         

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Payments/Index.cshtml
@model IEnumerable<Saloon.Models.Payment>

@{
    ViewBag.Title = "Employee Payments";
    Layout = "~/Views/Shared/_Layout.cshtml";
} 
<br />

<p>
    @Html.ActionLink("Create Payroll", "Create", "Payments", null, new {@class="btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            Employee
        </th>
        <th>
            Month
        </th>
        <th>
           Attended Customers
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            Comission 
        </th> 
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.Name)
        </td> 
        <td>
            @item.PayDate.ToString("MMMM, yyyy")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customers)
        </td>
        <td> 
            @String.Format("{0:0} %", item.Rate)
        </td>
        <td> 
            @String.Format("{0:#,##0 RWF}", item.Amount)
        </td>
    </tr>
}

</table>